[build] no more tools target, and install the mir-* scripts from assemble.sh so building the whole thing is easier

diff --git a/scripts/mir-run b/scripts/mir-run
--- a/scripts/mir-run
+++ b/scripts/mir-run
@@ -53,7 +53,11 @@ supported() {
     fi
     ;;
   node)
-   NODE=which node >/dev/null 2>&1 || (echo "Node binary not found"; exit 1)
+   NODE="$(which nodex >/dev/null 2>&1)"
+   if [ $? -ne 0 ]; then
+     echo "Node binary not found"
+     exit 1
+   fi
    ;;
   unix-*)
    # We assume tap is present for unix-direct and unix-socket to always work
